use_frameworks!

platform :ios, '8.0'

target 'LGEffective_Example' do
  pod 'LGEffective', :path => '../'

  target 'LGEffective_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
